Added missing <algorithm> include.
src/common/module.cc: In member function »bool google_breakpad::Module::AddFunction(Function*)«:
src/common/module.cc:175:52: fejl: »find_if« is not a member of »std«; did you mean »find«?
  175 |     FunctionSet::iterator existing_function = std::find_if(
      |                                                    ^~~~~~~
      |                                                    find
make: *** [Makefile:7965: src/common/tools_linux_dump_syms_dump_syms-module.o] Fejl 1